"""
Prompt templates and schemas for ConceptBridge AI.
"""

from .system_prompts import (
    CONCEPTBRIDGE_TEACHER_SYSTEM_PROMPT,
    ALTERNATIVE_STYLE_PROMPT,
    MISCONCEPTION_ANALYSIS_PROMPT,
    RECOMMENDATION_PROMPT,
)

__all__ = [
    "CONCEPTBRIDGE_TEACHER_SYSTEM_PROMPT",
    "ALTERNATIVE_STYLE_PROMPT",
    "MISCONCEPTION_ANALYSIS_PROMPT",
    "RECOMMENDATION_PROMPT",
]
